import mongoose from "mongoose";
const studentSchema = mongoose.Schema({
    enrollId:{
        type:String,
        required:true
    },
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true
    },
    gender:{
        type:String,
        required:true
    },
    date:{
        type:Date,
        required:true
    },
    contact:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    type:{
        type:String,
        required:true
    },
    joiningDate:{
        type:Date,
        required:true
    },
    gname:{
        type:String,
        required:true
    },    
    gcontact:{
        type:String,
        required:true
    },
    gaddress:{
        type:String,
        required:true
    },
    profilePic:{
        type:String,
        required:true
    },
    status:{
        type:Boolean,
        default:true
    },
    batchId:{
        type:String
    },
    feesStatus:{
        type:String
    },
    adminVerify:{
        type:String,
        default:"Not Verified"
    }
});
export default mongoose.model('studentSchema',studentSchema,'student');