export const status = {
    SUCCESS : 200,
    NOT_FOUND : 404,
    SERVER_ERROR : 500,
    UN_AUTHORIZE : 401
}

export const message = {
    LOGIN_SUCCESSFULL : "Login Successfull",
    SERVER_ERROR : "Internal server error",
    REGISTRATION_SUCCESSFULL : "Registration Successfull",
    SOMETHING_WENT_WRONG : "Something Went Wrong",
    NOT_MATCHED : "Email or Password Not Matched",
    FILE_NOT_UPLOADED:"File not uploaded",
    MAIL_SENT:"Mail Sent Please Verify",
    ADMIN_VERIFICATION_REQUIRED:"Email Verified | Please Wait for 24 Hours for Admin Approval",
    DATA_RECEIVED_SUCCESSFULLY:"Data Received Successfully",
    NO_RECORD_FOUND:"No Record Found",
    UPDATE_ERROR:"Error while Verifying",
    UPDATE_SUCCESSFULLY:"Employee Verification Successfull",
    ALREADY_VERIFIED:"Already Verified",
    ACCOUNT_DEACTIVATED:"Account De-Activated | Contact Admin to Re-Activate",
    ENQUIRY_REMARK : "Remark Added",
    UPLOAD_STATUS : "File Uploaded Successfully",
    MAIL_SENT_SYLLABUS:"Syllabus Sent in Mail",
    MAIL_NOT_SENT:"Error While sending Syllabus in mail",
    COURSE_ADDED:"Course Added Successfully",
    COURSE_NOT_ADDED:"Error while Adding Course",
    COURSE_ALREADY_EXIST:"Course Already Exist Please try with Another Name",
    DETAILED_SYLLABUS_MODIFIED:"Detailed Syllabus Modified",
    DETAILED_SYLLABUS_ADDED:"Detailed Syllabus Added",
    COURSE_AVAILABLE:"Course Already Available | Go to Update Section",
    BATCH_ADDED : "Batch Added Successfully",
    BATCH_ADD_ERROR : "Error while Adding Batch",
    ALLOCATION_SUCCESS:"Trainer Allocated Successfully",
    ASSIGNMENT_NOT_UPLOAD:"Error While Uploading Assignment",
    ASSIGNMENT_UPLOADED:"Assignment Uploaded Successfully",
    DOMAIN_ADDED:"Domain Added Successfully",
    DOMAIN_NOT_ADDED:"Error while Adding Domain",
    DOMAIN_UPDATED:"Domain Updated Successfully",
    DOMAIN_NOT_UPDATED:"Domain Not Updated",
    DOMAIN_DELETED:"Domain deleted Successfully",
    DOMAIN_NOT_DELETED:"Domain Not Deleted",
    INTERVIEW_QUESTIONS_ADDED:"Interview Questions Added",
    INTERVIEW_QUESTIONS_NOT_ADDED:"Issue While Adding Interview Questions",
    INTERVIEW_QUESTIONS_NOT_FOUND:"Interview Questions Not Found",
    LOW_INTERNET:"Check your Internet Connection",
    MAIL_SENT_FOR_ENROLL : "Mail Sent Successfully",
    BLOG_UPDATED : "Blog Updated Successfully",
    BLOG_NOT_UPDATED : "Error while Updating Blog",
    BLOG_DELETED : "Blog deleted Successfully",
    BLOG_NOT_DELETED : "Error while Deleting Blog",
    INTERVIEW_QUESTIONS_DELETED:"Interview Question Deleted Successfully",
    INTERVIEW_QUESTIONS_NOT_DELETED:"Interview Question Not Deleted",
    GLIMPHS_DELETED:"Glimphs Deleted Successfully",
    ADMIN_VERIFY_STUDENT:"Admin Verified Student",
    ADMIN_NOT_VERIFY_STUDENT:"Error while Verifying Student",
    LINK_UPLOADED:"Link Uploaded Successfully",
    LINK_NOT_UPLOADED : "Link Not Uploaded",
    LINK_DELETED:"Link Deleted Successfully",
    LINK_NOT_DELETED:"Link Not Deleted",
    LINK_UPDATE:"Link Updated Successfully",
    LINK_NOT_UPDATE:"Link not updated",
    COURSE_DELETED : "Course Deleted Successfully",
    COURSE_NOT_DELETED:"Course Not Deleted As It is Linked with Other Module",
    COURSE_UPDATED:"Course Updated Successfully",
    COURSE_NOT_UPDATED:"Course Not Updated",
    BATCH_ALLOCATED:"Batch Allocated Successfully",
    BATCH_ALREADY_ALLOCATED:"Batch Already Allocated",
}